source 'https://supermarket.getchef.com'

cookbook 'apt', '~> 7.4.0'
cookbook 'chef-solo-search', '~> 0.5.1'
cookbook 'docker', '~> 8.2.4'
cookbook 'hostnames', '~> 0.4.2'
cookbook 'nfs', '~> 5.0.0'
cookbook 'ntp', '~> 3.12.0'
cookbook 'openssh', '~> 2.9.2'
cookbook 'postfix', '~> 6.0.4'
cookbook 'poise-python', '~> 1.7.0'
cookbook 'sudo', '~> 5.4.7'
cookbook 'timezone_iii', '~> 1.1.7'
cookbook 'udev', '~> 0.2.0'
cookbook 'users', '~> 8.1.1'
