#!/bin/bash

# Initialize dbus
mkdir -p /var/run/dbus
rm -f /var/run/dbus/pid
dbus-daemon --system

# Initialize avahi-daemon
sed -i '/rlimit-nproc/d' /etc/avahi/avahi-daemon.conf
avahi-daemon -D

# Update Plex (if needed)
/sbin/update_plex

# Start Plex
exec setuser nobody /usr/sbin/start_pms
