#!/bin/bash

# Update Plex (if needed)
/sbin/update_plex

# Remove stale pid file if present
if [ -f '/config/Plex Media Server/plexmediaserver.pid' ]; then
  rm '/config/Plex Media Server/plexmediaserver.pid'
fi

# Start Plex
/usr/sbin/start_pms
