#!/bin/sh

#change these parameters in /etc/default/plexmediaserver
export PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6
export PLEX_MEDIA_SERVER_HOME=/usr/lib/plexmediaserver
export PLEX_MEDIA_SERVER_MAX_STACK_SIZE=3000
export PLEX_MEDIA_SERVER_TMPDIR=/tmp
export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR="${HOME}/Library/Application Support"

if [ -f /etc/default/locale ]; then
  export LANG="`cat /etc/default/locale|awk -F '=' '/LANG=/{print $2}'|sed 's/"//g'`"
  export LC_ALL="$LANG"
fi

test -f /etc/default/plexmediaserver && . /etc/default/plexmediaserver

if [ ! -d "$PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR" ]
then
  mkdir -p "$PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR"
  if [ ! $? -eq 0 ]
  then
    echo "WARNING COULDN'T CREATE $PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR, MAKE SURE I HAVE PERMISSON TO DO THAT!"
    exit 1
  fi
fi

export TMPDIR="${PLEX_MEDIA_SERVER_TMPDIR}"

echo "Max Plugin Procs: $PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS:"
echo "Max Stack Size: $PLEX_MEDIA_SERVER_MAX_STACK_SIZE"
echo "Support Dir: $PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR"
echo "LD Library Path: $LD_LIBRARY_PATH"

echo -n "Setting ulimit: "
ulimit -s $PLEX_MAX_STACK_SIZE

# Add sleep - Possible fix for start on boot.
sleep 3

cd $PLEX_MEDIA_SERVER_HOME
exec setuser $PLEX_MEDIA_SERVER_USER ./Plex\ Media\ Server
