#!/bin/bash

if [ ! -f /plexpy/PlexPy.py ]; then
  git clone https://github.com/drzoidberg33/plexpy.git
elif [ -f /plexpy/PlexPy.py ]; then
  cd /plexpy
  git pull
else
  echo "I don't know what to do."
  exit 127
fi

exec setuser nobody python /plexpy/PlexPy.py --datadir /config
