#!/bin/bash

# Initialize dbus
mkdir -p /var/run/dbus
rm -f /var/run/dbus/pid
dbus-daemon --system

# Initialize avahi-daemon
sed -i '/rlimit-nproc/d' /etc/avahi/avahi-daemon.conf
avahi-daemon -D

# Start netatalk
exec netatalk -d
