#!/bin/bash

if [ ! -f /certbot/certbot-auto ]; then
  git clone https://github.com/certbot/certbot.git
elif [ -f /certbot/certbot-auto ]; then
  cd /sabnzbd
  git pull
else
  echo "I don't know what to do."
  exit 127
fi

/certbot/certbot-auto -n --config-dir /data/configs/nginx/ssl renew
